# Generated by Django 5.0.6 on 2024-06-01 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_teacher_teachercoursehours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbookentry',
            name='created_by',
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
        migrations.AlterField(
            model_name='logbookentry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
    ]
