# Generated by Django 5.0.6 on 2024-06-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_logbookentry_created_by_logbookentry_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbookentry',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
    ]
